Update README.md
libraspberrypi-dev is needed for Pi OS Lite, it is not installed by default and thus bcm_host.h headers will not be on the system:

g++ -DMODEL_CP=1 a314d/a314d.cc -O3 -o bin_pi/a314d-cp
gcc a314d/start_gpclk.c -I/opt/vc/include -L/opt/vc/lib -lbcm_host -o bin_pi/start_gpclk
a314d/start_gpclk.c:13:10: fatal error: bcm_host.h: No such file or directory
   13 | #include <bcm_host.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:27: bin_pi/start_gpclk] Error 1
install: cannot stat 'bin_pi/start_gpclk': No such file or directory